[package]
name = "bai5"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
hex = "0.4"
num-bigint = "0.4"
num-traits = "0.2"
